import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Params } from "next/dist/shared/lib/router/utils/route-matcher";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  openGraph:{
    title:'next application',
    description:'this is a next application',
    type: 'website'
  }
};

// export async function generateMetadata({params}:{ params: Params }):Promise<Metadata>{
//   const id = params.id
//   const product = await fetch(`http://.../${id}`).then(res=>res.json())

//   return {
//     title: product.title,
//     description: product.description
//   }
// }

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
